### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by fermmm** [UBIC-repo/Whitepaper#1]
This is mentioned in the white paper as a vulnerability:

> Governments might be hostile to the idea of this kind of cryptocurrencies. They could then try to harm it through legislation or hacking. Because they are emitting the Document Signing Certificates they could spam the network with passport registration transaction, this however appears to be unlikely as it will certainly lower their credibility and damage them.

There is another factor that is not being taken into account: **Corruption**.
As you probably know, dominant classes with lots of money corrupt almost anyone. An employee of the state that is working on the signatures and ID creation can be bribed to create millions of fake IDS that will be used to completly destroy the system. There is no need to create phisical IDS, only digital data.
Also when the currency starts being used it's easier to destroy, it's the right moment to make this attack since less fake IDS are needed to create more damage. 

POI parties are not friendly but are the only solid proof of identity I know:
https://decentralize.today/ethereum-based-proof-of-individuality-prevents-sybil-attacks-9757864bbf61

**Comment by ubiubi18** [comment]
I doubt this is going to happen because it would at the same time destroy the trust in that countrys documents and therefor there is a high incentive for a country to stop and revert such actions.

It is all academic discussion as long as this project has only few dozen registered passports (10 up to day). But i trust the dev beeing passionate enough to carry this project further for month or even years until ubi in general reaches more attention and so will ubic. 

I would fear some other form of "corruption" -  delegated nodes (with a speculative few million user as voters) could be elected on the promise to slowly lowering the minting rate - Producing more scarcity which would would come in favor of early adopters and on cost of late adopters, next generations. 

Also i fear that if it takes 2-3 years to go viral with UBIC, the early adopter bonus for the first few registrants will be too exaggerated. A possible solution: as long as the project is centralized and not in the hands of more decentralized delegated nodes, the creator could cover that exaggerations by deciting that the minting rate for each country will be multiplied by faktor X as soon as every participating countrys currency has reached a certain treshold or as soon as ubic is close hiting the markets. But such a strategy should be mentioned early enough for example in the withepaper not to undermine trust?

Good luck

**Comment by fermmm** [comment]
> I doubt this is going to happen because it would destroy the trust in that countrys documents and therefor there is a high incentive for a country to stop and revert such actions.

The ruling class doesn't care about the state at all, who would revert these actions when the ruling class wins an election and takes the state? (this happens all the time everywhere). So this project is not inmune to the ruling class economic attacks.
