### ISSUE TITLE
Whitepaper unclear on what data is used to create the passport hash

### ISSUE THREAD

**Issue by Aaargh20318** [UBIC-repo/Whitepaper#18]
I'm wondering how the 'passport hash' is calculated, the whitepaper doesn't explain what exactly is hashed and how this proves I am holding a genuine passport.

**Comment by ubicorn** [comment]
It is described in the "Non-transferable proof of Signature Knowledge" section.

> The Non-transferable proof of Signature Knowledge is the key element that allows UBIC to operate by providing a way to decently and securely verify there is a link between an UBIC address and an unknown but genuine passport. It consists in proving the knowledge of a digital signature without revealing it.

https://github.com/UBIC-repo/Whitepaper#non-transferable-proof-of-signature-knowledge

**Comment by Aaargh20318** [comment]
It talks about a ‘hash of passport information’ but never explains what this passport information is. It also doesn’t prove the user is holding a genuine document and not a clone.

**Comment by ubicorn** [comment]
The passport hash is the hash of all the information contained on the NFC chip. Name, date of birth, facial image...
The verification is done by verifying a trust chain:
Step 1:
Verify that the hash is signed by a document signing certificate.
Steps 2:
Verify that the Document Signing Certificate is signed by a Country Signing Certificate Authority.
Steps 3:
Verify that the Country Signing Certificate Authority is trusted.

It is very similar to what happens when you use an automated passport gate and is very well described here: https://www.icao.int/Security/FAL/PKD/Pages/ePassportBasics.aspx

There are however 2 differences to when you use a passport gate.
The first one is that the automated passport gate will verify that the personal information on the passport match the hash that was signed by the Document Signing Certificate, this is not done when registering your passport on UBIC, you personal information are neither read nor published on the blockchain.
The second one is the use of a Non-transferable proof of Signature Knowledge. This is done in order to avoid passport registration transaction to be malleable, in the sense that someone could change the beneficiary address of the passport registration transaction.

Note that I had to skip some details to keep the description short.

**Comment by Aaargh20318** [comment]
The problem is that none of that information is secret. It's PII so you should be careful in who you give access to it, but others _do_ have access to it. For example the electronic passport gates you mention. So how do you ensure someone is using a genuine passport and not a copy ? You only prove that the data is genuine and untampered with, and the person has access to that data. You don't prove they are holding the physical, original document.

**Comment by ubicorn** [comment]
This is correct, one option could be to use the active authentication or chip authentication features. But they are not supported by all passports. It seems unlikely that a passport gates engages in such an activity anyway, the problem for them is that it will be known.
